%chk=test.chk
#p b3lyp/6-31g(d) superfinegrid scf=(fermi,novaracc)

Gaussian input file generated by gausspimom

0 1
Gd 1.5437014065 -1.6803756166 -0.0274688953
Gd 0.6832469286 2.1740437457 -0.0659329783
Gd -2.2271697065 -0.4926087437 -0.0435301155
O -0.6066332561 -1.9231056792 0.2634310091
O -1.3575818562 1.4828950928 0.3058176475
O 1.9656231742 0.4405083491 0.2876586439


--Link1--
%chk=test.chk
#p b3lyp guess=read stable=opt chkbasis geom=check

Gaussian input file generated by gausspimom (stability check)

0 1

